version: '2'
services:
    jhipstersamplemonapplication-app:
        image: jhipstersamplemonapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://jhipstersamplemonapplication-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterSampleMonApplication
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipstersamplemonapplication-elasticsearch:9300
        ports:
            - 8081:8081
    jhipstersamplemonapplication-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstersamplemonapplication-mongodb
    jhipstersamplemonapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstersamplemonapplication-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
